### ISSUE TITLE
Crashes on loading to due to NoClassDefFoundError on 'Iron Stair'

### ISSUE THREAD

**Issue by SpinWin** [Samlegamer/Macaw-s-Bridges-Compat#28]
> -- Head --
> Thread: Render thread
> Suspected Mods: NONE
> Stacktrace:
> 	at net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:447) ~[securemodules-2.2.10.jar!/:?] {}
> -- MOD macawsbridgesbop --
> Details:
> 	Caused by 0: java.lang.NoClassDefFoundError: com/mcwbridges/kikoz/objects/Iron_Stair
> 		at fr.samlegamer.macawsbridgesbop.MacawsBridgesBOP.<init>(MacawsBridgesBOP.java:29) ~[macawsbridgesbop-1.20-1.1.jar!/:1.20-1.1] {re:classloading}
> 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
> 		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> 		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> 		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:66) ~[javafmllanguage-1.20.4-49.0.38.jar!/:49.0.38] {}
> 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$5(ModContainer.java:125) ~[fmlcore-1.20.4-49.0.38.jar!/:1.0] {}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
> 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
> 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
> 
> 	Mod File: /D:/New folder/Instances/Custom/mods/macawsbridgesbop-1.20-1.1.jar
> 	Failure message: Macaw's Bridges - BOP (macawsbridgesbop) has failed to load correctly
> 		java.lang.NoClassDefFoundError: com/mcwbridges/kikoz/objects/Iron_Stair
> 	Mod Version: 1.20-1.1
> 	Mod Issue URL: https://github.com/Samlegamer/Macaw-s-Bridges-Compat/issues
> 	Exception message: java.lang.ClassNotFoundException: com.mcwbridges.kikoz.objects.Iron_Stair
> Stacktrace:
> 	at net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:447) ~[securemodules-2.2.10.jar!/:?] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
> 	at fr.samlegamer.macawsbridgesbop.MacawsBridgesBOP.<init>(MacawsBridgesBOP.java:29) ~[macawsbridgesbop-1.20-1.1.jar!/:1.20-1.1] {re:classloading}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:66) ~[javafmllanguage-1.20.4-49.0.38.jar!/:49.0.38] {}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$5(ModContainer.java:125) ~[fmlcore-1.20.4-49.0.38.jar!/:1.0] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by Samlegamer** [comment]
Fixed in 1.20-1.2

**Comment by judicius96** [comment]
Will this be fixed in older versions of MC since Macaw backported the 3.0 changes? Explicitly asking for 1.19.2

**Comment by Samlegamer** [comment]
yes fixed in 1.16.5/1.17.1/1.18.2/1.19/1.19.2/1.19.3/1.19.4/1.20/1.20.4

**Comment by judicius96** [comment]
This is still happening on the Abnormals Compat mod, is it still supported?

**Comment by theshadowake** [comment]
Issue still happens with:
https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-aurora

**Comment by theshadowake** [comment]
(1.18.2)

**Comment by Samlegamer** [comment]
normally fixed
